export const bankLogos = [
    { name: "MB Bank", URL: "https://cdn.haitrieu.com/wp-content/uploads/2022/02/Icon-MB-Bank-MBB.png", width: 25, height: 25, marginRight: 10 },
    { name: "Techcombank", URL: "https://img7.thuthuatphanmem.vn/uploads/2023/07/06/mau-logo-techcombank-dep_045648494.png", width: 40, height: 25 , marginRight: 3},
    { name: "Vietcombank", URL: "https://cdn.haitrieu.com/wp-content/uploads/2022/02/Icon-Vietcombank.png", width: 25, height: 25, marginRight: 10},
    { name: "Vietinbank", URL: "https://cdn.haitrieu.com/wp-content/uploads/2022/01/Logo-VietinBank-CTG-Ori.png", width: 28, height: 28, marginRight: 10},
    { name: "Agribank", URL: "https://cdn.haitrieu.com/wp-content/uploads/2022/01/Icon-Agribank.png", width: 25, height: 25, marginRight: 10},
    { name: "VPBank", URL: "https://cdn.haitrieu.com/wp-content/uploads/2022/01/Icon-VPBank.png", width: 25, height: 25, marginRight: 10},
    { name: "HDBank", URL: "https://cdn.haitrieu.com/wp-content/uploads/2022/01/Logo-HDBank-Ori.png", width: 30, height: 30, marginRight: 10},
    { name: "BIDV", URL: "https://cdn.haitrieu.com/wp-content/uploads/2022/01/Icon-BIDV-.png", width: 25, height: 25, marginRight: 10},
    { name: "ACB", URL: "https://cdn.haitrieu.com/wp-content/uploads/2022/01/Logo-ACB-Ori.png", width: 25, height: 25, marginRight: 10},
    { name: "VIB", URL: "https://companieslogo.com/img/orig/VIB.VN-11af05f7.png?t=1723177756", width: 28.77, height: 25, marginRight: 10},
    { name: "SHB", URL: "https://cdn.haitrieu.com/wp-content/uploads/2022/02/Icon-SHB.png", width: 25, height: 25, marginRight: 10},
    { name: "SCB", URL: "https://cdn.haitrieu.com/wp-content/uploads/2022/02/Icon-SCB.png", width: 25, height: 25, marginRight: 10},
    { name: "Co-opBank", URL: "https://sanfactory.vn/wp-content/uploads/2023/10/Co-opbank-1.png", width: 25, height: 25, marginRight: 10},
    { name: "OCB", URL: "https://cdn.haitrieu.com/wp-content/uploads/2022/02/Icon-OCB.png", width: 25, height: 25, marginRight: 10},
    { name: "Oceanbank", URL: "https://cdn.haitrieu.com/wp-content/uploads/2022/02/Icon-OceanBank.png", width: 25, height: 25, marginRight: 10},
    { name: "VNPay", URL: "https://cdn.haitrieu.com/wp-content/uploads/2022/10/Icon-VNPAY-QR.png", width: 32, height: 25, marginRight: 10},
    { name: "MoMo", URL: "https://cdn.haitrieu.com/wp-content/uploads/2022/10/Logo-MoMo-Circle.png", width: 28, height: 28, marginRight: 10},
    { name: "ZaloPay", URL: "https://cdn.haitrieu.com/wp-content/uploads/2022/10/Logo-ZaloPay-Square.png", width: 25, height: 25, marginRight: 10},
    { name: "MSB", URL: "https://cdn.haitrieu.com/wp-content/uploads/2022/02/Icon-MSB.png", width: 41.5, height: 25, marginRight: 10},
]