services:

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${pg_user}
      POSTGRES_PASSWORD: ${pg_password}
      POSTGRES_DB: ${pg_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  web_backend:
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      PYTHONPATH: /app
      REDIS_HOST: redis
      DB_URL: ${DB_URL}
    networks:
      - app-network
    depends_on:
      - redis
      - postgres
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  web_frontend_admin:
    build:
      context: ./frontend/admin_hr_management
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/admin_hr_management:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_HOST=0.0.0.0
      - VITE_APP_TYPE=admin
    networks:
      - app-network
    command: npm run dev -- --host 0.0.0.0

  web_frontend_user:
    build:
      context: ./frontend/User
      dockerfile: Dockerfile
    ports:
      - "5174:5174"
    volumes:
      - ./frontend/User:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_HOST=0.0.0.0
      - VITE_APP_TYPE=user
    networks:
      - app-network
    command: npm run dev -- --host 0.0.0.0

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: