export const world_countries = [
    { value: 'AF', code: 'AF', label: 'Afghanistan', id: 'AFG' },
    { value: 'AL', code: 'AL', label: 'Albania', id: 'ALB' },
    { value: 'DZ', code: 'DZ', label: 'Algeria', id: 'DZA' },
    { value: 'AD', code: 'AD', label: 'Andorra', id: 'AND' },
    { value: 'AO', code: 'AO', label: 'Angola', id: 'AGO' },
    { value: 'AG', code: 'AG', label: 'Antigua and Barbuda', id: 'ATG' },
    { value: 'AR', code: 'AR', label: 'Argentina', id: 'ARG' },
    { value: 'AM', code: 'AM', label: 'Armenia', id: 'ARM' },
    { value: 'AU', code: 'AU', label: 'Australia', id: 'AUS' },
    { value: 'AT', code: 'AT', label: 'Austria', id: 'AUT' },
    { value: 'AZ', code: 'AZ', label: 'Azerbaijan', id: 'AZE' },
    { value: 'BS', code: 'BS', label: 'Bahamas', id: 'BHS' },
    { value: 'BH', code: 'BH', label: 'Bahrain', id: 'BHR' },
    { value: 'BD', code: 'BD', label: 'Bangladesh', id: 'BGD' },
    { value: 'BB', code: 'BB', label: 'Barbados', id: 'BRB' },
    { value: 'BY', code: 'BY', label: 'Belarus', id: 'BLR' },
    { value: 'BE', code: 'BE', label: 'Belgium', id: 'BEL' },
    { value: 'BZ', code: 'BZ', label: 'Belize', id: 'BLZ' },
    { value: 'BJ', code: 'BJ', label: 'Benin', id: 'BEN' },
    { value: 'BT', code: 'BT', label: 'Bhutan', id: 'BTN' },
    { value: 'BO', code: 'BO', label: 'Bolivia', id: 'BOL' },
    { value: 'BA', code: 'BA', label: 'Bosnia and Herzegovina', id: 'BIH' },
    { value: 'BW', code: 'BW', label: 'Botswana', id: 'BWA' },
    { value: 'BR', code: 'BR', label: 'Brazil', id: 'BRA' },
    { value: 'BN', code: 'BN', label: 'Brunei', id: 'BRN' },
    { value: 'BG', code: 'BG', label: 'Bulgaria', id: 'BGR' },
    { value: 'BF', code: 'BF', label: 'Burkina Faso', id: 'BFA' },
    { value: 'BI', code: 'BI', label: 'Burundi', id: 'BDI' },
    { value: 'KH', code: 'KH', label: 'Cambodia', id: 'KHM' },
    { value: 'CM', code: 'CM', label: 'Cameroon', id: 'CMR' },
    { value: 'CA', code: 'CA', label: 'Canada', id: 'CAN' },
    { value: 'CV', code: 'CV', label: 'Cape Verde', id: 'CPV' },
    { value: 'KY', code: 'KY', label: 'Cayman Islands', id: 'CYM' },
    { value: 'CF', code: 'CF', label: 'Central African Republic', id: 'CAF' },
    { value: 'TD', code: 'TD', label: 'Chad', id: 'TCD' },
    { value: 'CL', code: 'CL', label: 'Chile', id: 'CHL' },
    { value: 'CN', code: 'CN', label: 'China', id: 'CHN' },
    { value: 'CO', code: 'CO', label: 'Colombia', id: 'COL' },
    { value: 'KM', code: 'KM', label: 'Comoros', id: 'COM' },
    { value: 'CG', code: 'CG', label: 'Congo', id: 'COG' },
    { value: 'CD', code: 'CD', label: 'Democratic Republic of the Congo', id: 'COD' },
    { value: 'CR', code: 'CR', label: 'Costa Rica', id: 'CRI' },
    { value: 'CI', code: 'CI', label: 'Ivory Coast', id: 'CIV' },
    { value: 'HR', code: 'HR', label: 'Croatia', id: 'HRV' },
    { value: 'CU', code: 'CU', label: 'Cuba', id: 'CUB' },
    { value: 'CY', code: 'CY', label: 'Cyprus', id: 'CYP' },
    { value: 'CZ', code: 'CZ', label: 'Czech Republic', id: 'CZE' },
    { value: 'DK', code: 'DK', label: 'Denmark', id: 'DNK' },
    { value: 'DJ', code: 'DJ', label: 'Djibouti', id: 'DJI' },
    { value: 'DM', code: 'DM', label: 'Dominica', id: 'DMA' },
    { value: 'DO', code: 'DO', label: 'Dominican Republic', id: 'DOM' },
    { value: 'EC', code: 'EC', label: 'Ecuador', id: 'ECU' },
    { value: 'EG', code: 'EG', label: 'Egypt', id: 'EGY' },
    { value: 'SV', code: 'SV', label: 'El Salvador', id: 'SLV' },
    { value: 'GQ', code: 'GQ', label: 'Equatorial Guinea', id: 'GNQ' },
    { value: 'ER', code: 'ER', label: 'Eritrea', id: 'ERI' },
    { value: 'EE', code: 'EE', label: 'Estonia', id: 'EST' },
    { value: 'SZ', code: 'SZ', label: 'Eswatini', id: 'SWZ' },
    { value: 'ET', code: 'ET', label: 'Ethiopia', id: 'ETH' },
    { value: 'FK', code: 'FK', label: 'Falkland Islands', id: 'FLK' },
    { value: 'FO', code: 'FO', label: 'Faroe Islands', id: 'FRO' },
    { value: 'FJ', code: 'FJ', label: 'Fiji', id: 'FJI' },
    { value: 'FI', code: 'FI', label: 'Finland', id: 'FIN' },
    { value: 'FR', code: 'FR', label: 'France', id: 'FRA' },
    { value: 'GF', code: 'GF', label: 'French Guiana', id: 'GUF' },
    { value: 'PF', code: 'PF', label: 'French Polynesia', id: 'PYF' },
    { value: 'GA', code: 'GA', label: 'Gabon', id: 'GAB' },
    { value: 'GM', code: 'GM', label: 'Gambia', id: 'GMB' },
    { value: 'GE', code: 'GE', label: 'Georgia', id: 'GEO' },
    { value: 'DE', code: 'DE', label: 'Germany', id: 'DEU' },
    { value: 'GH', code: 'GH', label: 'Ghana', id: 'GHA' },
    { value: 'GI', code: 'GI', label: 'Gibraltar', id: 'GIB' },
    { value: 'GR', code: 'GR', label: 'Greece', id: 'GRC' },
    { value: 'GL', code: 'GL', label: 'Greenland', id: 'GRL' },
    { value: 'GD', code: 'GD', label: 'Grenada', id: 'GRD' },
    { value: 'GU', code: 'GU', label: 'Guam', id: 'GUM' },
    { value: 'GT', code: 'GT', label: 'Guatemala', id: 'GTM' },
    { value: 'GG', code: 'GG', label: 'Guernsey', id: 'GGY' },
    { value: 'GN', code: 'GN', label: 'Guinea', id: 'GIN' },
    { value: 'GW', code: 'GW', label: 'Guinea-Bissau', id: 'GNB' },
    { value: 'GY', code: 'GY', label: 'Guyana', id: 'GUY' },
    { value: 'HT', code: 'HT', label: 'Haiti', id: 'HTI' },
    { value: 'HN', code: 'HN', label: 'Honduras', id: 'HND' },
    { value: 'HK', code: 'HK', label: 'Hong Kong', id: 'HKG' },
    { value: 'HU', code: 'HU', label: 'Hungary', id: 'HUN' },
    { value: 'IS', code: 'IS', label: 'Iceland', id: 'ISL' },
    { value: 'IN', code: 'IN', label: 'India', id: 'IND' },
    { value: 'ID', code: 'ID', label: 'Indonesia', id: 'IDN' },
    { value: 'IR', code: 'IR', label: 'Iran', id: 'IRN' },
    { value: 'IQ', code: 'IQ', label: 'Iraq', id: 'IRQ' },
    { value: 'IE', code: 'IE', label: 'Ireland', id: 'IRL' },
    { value: 'IL', code: 'IL', label: 'Israel', id: 'ISR' },
    { value: 'IT', code: 'IT', label: 'Italy', id: 'ITA' },
    { value: 'JM', code: 'JM', label: 'Jamaica', id: 'JAM' },
    { value: 'JP', code: 'JP', label: 'Japan', id: 'JPN' },
    { value: 'JE', code: 'JE', label: 'Jersey', id: 'JEY' },
    { value: 'JO', code: 'JO', label: 'Jordan', id: 'JOR' },
    { value: 'KZ', code: 'KZ', label: 'Kazakhstan', id: 'KAZ' },
    { value: 'KE', code: 'KE', label: 'Kenya', id: 'KEN' },
    { value: 'KI', code: 'KI', label: 'Kiribati', id: 'KIR' },
    { value: 'KR', code: 'KR', label: 'South Korea', id: 'KOR' },
    { value: 'KW', code: 'KW', label: 'Kuwait', id: 'KWT' },
    { value: 'KG', code: 'KG', label: 'Kyrgyzstan', id: 'KGZ' },
    { value: 'LA', code: 'LA', label: 'Laos', id: 'LAO' },
    { value: 'LV', code: 'LV', label: 'Latvia', id: 'LVA' },
    { value: 'LB', code: 'LB', label: 'Lebanon', id: 'LBN' },
    { value: 'LS', code: 'LS', label: 'Lesotho', id: 'LSO' },
    { value: 'LR', code: 'LR', label: 'Liberia', id: 'LBR' },
    { value: 'LY', code: 'LY', label: 'Libya', id: 'LBY' },
    { value: 'LI', code: 'LI', label: 'Liechtenstein', id: 'LIE' },
    { value: 'LT', code: 'LT', label: 'Lithuania', id: 'LTU' },
    { value: 'LU', code: 'LU', label: 'Luxembourg', id: 'LUX' },
    { value: 'MO', code: 'MO', label: 'Macau', id: 'MAC' },
    { value: 'MK', code: 'MK', label: 'North Macedonia', id: 'MKD' },
    { value: 'MG', code: 'MG', label: 'Madagascar', id: 'MDG' },
    { value: 'MW', code: 'MW', label: 'Malawi', id: 'MWI' },
    { value: 'MY', code: 'MY', label: 'Malaysia', id: 'MYS' },
    { value: 'MV', code: 'MV', label: 'Maldives', id: 'MDV' },
    { value: 'ML', code: 'ML', label: 'Mali', id: 'MLI' },
    { value: 'MT', code: 'MT', label: 'Malta', id: 'MLT' },
    { value: 'MH', code: 'MH', label: 'Marshall Islands', id: 'MHL' },
    { value: 'MQ', code: 'MQ', label: 'Martinique', id: 'MTQ' },
    { value: 'MR', code: 'MR', label: 'Mauritania', id: 'MRT' },
    { value: 'MU', code: 'MU', label: 'Mauritius', id: 'MUS' },
    { value: 'YT', code: 'YT', label: 'Mayotte', id: 'MYT' },
    { value: 'MX', code: 'MX', label: 'Mexico', id: 'MEX' },
    { value: 'FM', code: 'FM', label: 'Micronesia', id: 'FSM' },
    { value: 'MD', code: 'MD', label: 'Moldova', id: 'MDA' },
    { value: 'MC', code: 'MC', label: 'Monaco', id: 'MCO' },
    { value: 'MN', code: 'MN', label: 'Mongolia', id: 'MNG' },
    { value: 'ME', code: 'ME', label: 'Montenegro', id: 'MNE' },
    { value: 'MS', code: 'MS', label: 'Montserrat', id: 'MSR' },
    { value: 'MA', code: 'MA', label: 'Morocco', id: 'MAR' },
    { value: 'MZ', code: 'MZ', label: 'Mozambique', id: 'MOZ' },
    { value: 'MM', code: 'MM', label: 'Myanmar', id: 'MMR' },
    { value: 'NA', code: 'NA', label: 'Namibia', id: 'NAM' },
    { value: 'NR', code: 'NR', label: 'Nauru', id: 'NRU' },
    { value: 'NP', code: 'NP', label: 'Nepal', id: 'NPL' },
    { value: 'NL', code: 'NL', label: 'Netherlands', id: 'NLD' },
    { value: 'NC', code: 'NC', label: 'New Caledonia', id: 'NCL' },
    { value: 'NZ', code: 'NZ', label: 'New Zealand', id: 'NZL' },
    { value: 'NI', code: 'NI', label: 'Nicaragua', id: 'NIC' },
    { value: 'NE', code: 'NE', label: 'Niger', id: 'NER' },
    { value: 'NG', code: 'NG', label: 'Nigeria', id: 'NGA' },
    { value: 'NU', code: 'NU', label: 'Niue', id: 'NIU' },
    { value: 'NF', code: 'NF', label: 'Norfolk Island', id: 'NFK' },
    { value: 'MP', code: 'MP', label: 'Northern Mariana Islands', id: 'MNP' },
    { value: 'NO', code: 'NO', label: 'Norway', id: 'NOR' },
    { value: 'OM', code: 'OM', label: 'Oman', id: 'OMN' },
    { value: 'PK', code: 'PK', label: 'Pakistan', id: 'PAK' },
    { value: 'PW', code: 'PW', label: 'Palau', id: 'PLW' },
    { value: 'PS', code: 'PS', label: 'Palestine', id: 'PSE' },
    { value: 'PA', code: 'PA', label: 'Panama', id: 'PAN' },
    { value: 'PG', code: 'PG', label: 'Papua New Guinea', id: 'PNG' },
    { value: 'PY', code: 'PY', label: 'Paraguay', id: 'PRY' },
    { value: 'PE', code: 'PE', label: 'Peru', id: 'PER' },
    { value: 'PH', code: 'PH', label: 'Philippines', id: 'PHL' },
    { value: 'PN', code: 'PN', label: 'Pitcairn Islands', id: 'PCN' },
    { value: 'PL', code: 'PL', label: 'Poland', id: 'POL' },
    { value: 'PT', code: 'PT', label: 'Portugal', id: 'PRT' },
    { value: 'PR', code: 'PR', label: 'Puerto Rico', id: 'PRI' },
    { value: 'QA', code: 'QA', label: 'Qatar', id: 'QAT' },
    { value: 'RE', code: 'RE', label: 'Reunion', id: 'REU' },
    { value: 'RO', code: 'RO', label: 'Romania', id: 'ROU' },
    { value: 'RU', code: 'RU', label: 'Russia', id: 'RUS' },
    { value: 'RW', code: 'RW', label: 'Rwanda', id: 'RWA' },
    { value: 'BL', code: 'BL', label: 'Saint Barthelemy', id: 'BLM' },
    { value: 'SH', code: 'SH', label: 'Saint Helena', id: 'SHN' },
    { value: 'KN', code: 'KN', label: 'Saint Kitts and Nevis', id: 'KNA' },
    { value: 'LC', code: 'LC', label: 'Saint Lucia', id: 'LCA' },
    { value: 'MF', code: 'MF', label: 'Saint Martin', id: 'MAF' },
    { value: 'SX', code: 'SX', label: 'Sint Maarten', id: 'SXM' },
    { value: 'SM', code: 'SM', label: 'San Marino', id: 'SMR' },
    { value: 'ST', code: 'ST', label: 'Sao Tome and Principe', id: 'STP' },
    { value: 'SA', code: 'SA', label: 'Saudi Arabia', id: 'SAU' },
    { value: 'SN', code: 'SN', label: 'Senegal', id: 'SEN' },
    { value: 'RS', code: 'RS', label: 'Serbia', id: 'SRB' },
    { value: 'SC', code: 'SC', label: 'Seychelles', id: 'SYC' },
    { value: 'SL', code: 'SL', label: 'Sierra Leone', id: 'SLE' },
    { value: 'SG', code: 'SG', label: 'Singapore', id: 'SGP' },
    { value: 'SK', code: 'SK', label: 'Slovakia', id: 'SVK' },
    { value: 'SI', code: 'SI', label: 'Slovenia', id: 'SVN' },
    { value: 'SB', code: 'SB', label: 'Solomon Islands', id: 'SLB' },
    { value: 'SO', code: 'SO', label: 'Somalia', id: 'SOM' },
    { value: 'ZA', code: 'ZA', label: 'South Africa', id: 'ZAF' },
    { value: 'GS', code: 'GS', label: 'South Georgia', id: 'SGS' },
    { value: 'SS', code: 'SS', label: 'South Sudan', id: 'SSD' },
    { value: 'ES', code: 'ES', label: 'Spain', id: 'ESP' },
    { value: 'LK', code: 'LK', label: 'Sri Lanka', id: 'LKA' },
    { value: 'SD', code: 'SD', label: 'Sudan', id: 'SDN' },
    { value: 'SR', code: 'SR', label: 'Suriname', id: 'SUR' },
    { value: 'SJ', code: 'SJ', label: 'Svalbard', id: 'SJM' },
    { value: 'SE', code: 'SE', label: 'Sweden', id: 'SWE' },
    { value: 'CH', code: 'CH', label: 'Switzerland', id: 'CHE' },
    { value: 'SY', code: 'SY', label: 'Syria', id: 'SYR' },
    { value: 'TW', code: 'TW', label: 'Taiwan', id: 'TWN' },
    { value: 'TJ', code: 'TJ', label: 'Tajikistan', id: 'TJK' },
    { value: 'TZ', code: 'TZ', label: 'Tanzania', id: 'TZA' },
    { value: 'TH', code: 'TH', label: 'Thailand', id: 'THA' },
    { value: 'TL', code: 'TL', label: 'Timor-Leste', id: 'TLS' },
    { value: 'TG', code: 'TG', label: 'Togo', id: 'TGO' },
    { value: 'TK', code: 'TK', label: 'Tokelau', id: 'TKL' },
    { value: 'TO', code: 'TO', label: 'Tonga', id: 'TON' },
    { value: 'TT', code: 'TT', label: 'Trinidad and Tobago', id: 'TTO' },
    { value: 'TN', code: 'TN', label: 'Tunisia', id: 'TUN' },
    { value: 'TR', code: 'TR', label: 'Turkey', id: 'TUR' },
    { value: 'TM', code: 'TM', label: 'Turkmenistan', id: 'TKM' },
    { value: 'TC', code: 'TC', label: 'Turks and Caicos Islands', id: 'TCA' },
    { value: 'TV', code: 'TV', label: 'Tuvalu', id: 'TUV' },
    { value: 'UG', code: 'UG', label: 'Uganda', id: 'UGA' },
    { value: 'UA', code: 'UA', label: 'Ukraine', id: 'UKR' },
    { value: 'AE', code: 'AE', label: 'United Arab Emirates', id: 'ARE' },
    { value: 'GB', code: 'GB', label: 'United Kingdom', id: 'GBR' },
    { value: 'US', code: 'US', label: 'United States', id: 'USA' },
    { value: 'UY', code: 'UY', label: 'Uruguay', id: 'URY' },
    { value: 'UZ', code: 'UZ', label: 'Uzbekistan', id: 'UZB' },
    { value: 'VU', code: 'VU', label: 'Vanuatu', id: 'VUT' },
    { value: 'VA', code: 'VA', label: 'Vatican City', id: 'VAT' },
    { value: 'VE', code: 'VE', label: 'Venezuela', id: 'VEN' },
    { value: 'VN', code: 'VN', label: 'Vietnam', id: 'VNM' },
    { value: 'WF', code: 'WF', label: 'Wallis and Futuna', id: 'WLF' },
    { value: 'EH', code: 'EH', label: 'Western Sahara', id: 'ESH' },
    { value: 'YE', code: 'YE', label: 'Yemen', id: 'YEM' },
    { value: 'ZM', code: 'ZM', label: 'Zambia', id: 'ZMB' },
    { value: 'ZW', code: 'ZW', label: 'Zimbabwe', id: 'ZWE' },
];
